Repository gardener/machine-controller-manager-provider-azure, pull requests merged in 2023-12, with the labels that each got.

#121 switch GCR -> Artifact-Registry
  .ci/pipeline_definitions
  Makefile
  kubernetes/deployment.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/s

#120 Deal with terminal state vm in deleteMachine
  pkg/azure/utils.go
Labels: reviewed/lgtm, needs/ok-to-test, size/s

#124 Fixed the makefile
  Makefile
Labels: reviewed/lgtm, needs/ok-to-test, size/xs
