Repository gardener/machine-controller-manager-provider-azure, pull requests merged in 2024-07, with the labels that each got.

#157 Always use passed ConnectConfig when creating clients
  pkg/azure/access/factory.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#159 Update go version to 1.22.5
  .ci/pipeline_definitions
  Dockerfile
  go.mod
  pkg/azure/provider/helpers/driver.go
Labels: needs/ok-to-test, needs/review, size/xs

#139 Replace golint with golangci-lint
  .ci/check
  .golangci.yaml
  Makefile
  pkg/azure/api/validation/validation_test.go
  pkg/azure/instrument/instrument_test.go
  pkg/azure/provider/helpers/driver.go
  pkg/azure/provider/helpers/machineclass_test.go
  pkg/azure/provider/helpers/resourcegraphprocessor.go
  pkg/azure/provider/provider_test.go
  pkg/azure/testhelp/errors.go
  pkg/azure/testhelp/fakes/diskaccess.go
  pkg/azure/testhelp/fakes/imageaccess.go
  pkg/azure/testhelp/fakes/machineresources.go
  pkg/azure/testhelp/fakes/marketplaceagreementaccess.go
  pkg/azure/testhelp/fakes/nicaccess.go
  pkg/azure/testhelp/fakes/resourcegraphaccess.go
  pkg/azure/testhelp/fakes/resourcegroupaccess.go
  pkg/azure/testhelp/fakes/subnetaccess.go
  pkg/azure/testhelp/fakes/vmaccess.go
  pkg/azure/utils/checks.go
  pkg/azure/utils/names_test.go
  test/integration/provider/rti.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/l

#161 Fixed some errors from the linter
  pkg/azure/api/validation/validation_test.go
  pkg/azure/provider/helpers/connectconfig_test.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#164 [Cherry-pick rel-v0.13] Merge pull request #157 from AndreasBurger/az-clouds-pt2
  pkg/azure/access/factory.go
Labels: needs/ok-to-test, needs/review, size/xs
